GET http://localhost:3001/api/v1/automobiles

###

POST http://localhost:3001/api/v1/automobiles
Content-Type: application/json

{
  "title": "Toyota Camry GLE 2009",
  "description": "Really good quality car",
  "color": "white",
  "interiorColor": "black",
  "vin": 1234,
  "type": "Sedan"
}
