
GET http://localhost:3001/api/v1/users
Content-Type: application/json
Authorization: Bearer xxx


###
POST  http://localhost:3001/api/v1/users/signup
Content-Type: application/json

{  "email": "biruk@miu.edu", "password": "123", "fullname": "Biruk Yemane" }


###
POST  http://localhost:3001/api/v1/users/login
Content-Type: application/json

{  "email": "zaman@miu.edu", "password": "123" }


###

GET http://localhost:3001/api/v1/automobiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE1MTllY2U2ZTEyOGRhODViZDk0NWMiLCJlbWFpbCI6InphbWFuQG1pdS5lZHUiLCJmdWxsbmFtZSI6Im1vbmlyIHphbWFuIiwiaWF0IjoxNjc5MjU3ODg5fQ.7Rp4Rik8e--dPRmxFojBOQHaWM_ss5Sm4oCKijofXe0